version: "3.8"
# https://github.com/Kludex/fastapi-prometheus-grafana

volumes:
  prometheus-data:
  grafana-data:


services:
  app:
    container_name: app
    env_file:
      - ./src/monitoring_with_prometheus/variables_docker.env
    build:
      context: ./src/monitoring_with_prometheus
      dockerfile: Dockerfile
    volumes:
      - ./src/monitoring_with_prometheus:/app
    ports:
      - 5050:8082
    restart: unless-stopped
    # networks:
    #   example-network:
    #     ipv4_address: 172.16.238.10

  prometheus:
    container_name: prometheus
    env_file:
      - ./src/prometheus/variables_docker.env
    image: prom/prometheus:latest
    volumes:
      - ./src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    restart: unless-stopped
    # networks:
    #   example-network:
    #     ipv4_address: 172.16.238.11

  grafana:
    container_name: grafana
    env_file:
      - ./src/grafana/config.monitoring
    user: "472"
    image: grafana/grafana:latest
    volumes:
      - ./src/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - prometheus
    #   networks:
    #     example-network:
    #       ipv4_address: 172.16.238.12

    # networks:
    #   example-network:
    #     name: ${NETWORK_NAME}
    #     driver: bridge
    #     ipam:
    #       driver: default
    #       config:
    #         - subnet: 172.16.238.0/24
